; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
extra_configs = secrets.ini

[env:adafruit_feather_esp32_v2]

platform = espressif32
board = adafruit_feather_esp32_v2
framework = espidf
monitor_speed = 115200


build_flags =
    ; Pull from secrets.ini
    -D WIFI_SSID=\"${common_secrets.wifi_ssid}\"
    -D WIFI_PASS=\"${common_secrets.wifi_pass}\"
    -D HOST_IP=\"${common_secrets.host_ip}\"
    ; Hardware Config (Static Pins)
    -D I2S_SCK_PIN=14
    -D I2S_WS_PIN=15
    -D I2S_SD_PIN=32
    -D SAMPLE_RATE=44100
    -D READ_LEN=1024
    -D HOST_PORT=8001
    ;"{'sensor_id': 'sensor_001', 'api_key': 'key123', 'location': 'Raymond Laptop'}";
    -DSENSOR_ID=\"sensor_001\"
    -DAPI_KEY=\"key123\"
    -DLOCATION=\"Laptop\"
